# Generated by Django 3.2.13 on 2022-05-04 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0002_advertisement_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='favorite',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
