# Generated by Django 3.2.13 on 2022-05-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='favorite',
        ),
    ]
