# Generated by Django 3.2.13 on 2022-04-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
