# Generated by Django 3.2.13 on 2022-04-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20220426_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='measurements',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensors',
            field=models.ManyToManyField(related_name='measurements', to='measurement.Sensor'),
        ),
    ]
