# Generated by Django 3.2.13 on 2022-04-29 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_auto_20220430_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockproduct',
            options={'verbose_name': 'Товар на складе', 'verbose_name_plural': 'Товары на складе'},
        ),
    ]
